# Лабораторная работа №1

## Выполнила студентка группы БСТ1902 Кунафина Р.Р.

### Задание №1

In [1]:
print('Hello world!')

Hello world!


### Задание №2

Написать генератор случайных матриц(многомерных), который принимает опциональные параметры m, n, min_limit, max_limit, где m и n указывают размер матрицы, а min_lim и max_lim - минимальное и максимальное значение для генерируемого числа. По умолчанию при отсутствии параметров принимать следующие значения: m = 50 n = 50 min_limit = -250 max_limit = 1000 + (номер своего варианта)

In [2]:
import random
import numpy
import time


def generateMatrix(m = 50, n = 50, min_limit = -250, max_limit = 1010):
    """
    m - число строк матрицы;
    n - число столбцов матрицы;
    min_limit - минимальное значение генерируемого числа;
    max_limit - максимальное значение генерируемого числа;
    """
    matrix = numpy.empty((m, n))
    for i in range(m):
        for j in range(n):
            matrix[i][j] = random.randint(min_limit, max_limit)
    return matrix.astype(int)

### Задание №3

Реализовать методы сортировки строк числовой матрицы в соответствии с заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со временем стандартной функции сортировки. Испытания проводить на сгенерированных матрицах

Функция для применения сортировки к матрице

In [3]:
def sortMatrix(matrix, sortType):
    """
    matrix - матрица для сортировки
    sortType - функция необходимой сортировки
    Возвращает время, затраченное на сортировку матрицы, не изменяя саму матрицу
    """
    matrixC = matrix.copy()
    startTime = time.perf_counter()
    for row in matrixC:
        sortType(row)
    return time.perf_counter() - startTime

### Стандартная функция сортировки

In [4]:
def defaultSort(arr):
    arr.sort()

### Сортировка выбором

In [5]:
def selectionSort(arr): 
    for i in range(len(arr) - 1):
        smallest = i
        for j in range(i + 1, len(arr)):
            if arr[smallest] > arr[j]:
                smallest = j
        arr[i], arr[smallest] = arr[smallest], arr[i]

### Сортировка вставкой

In [6]:
def insertionSort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key

### Сортировка обменом

In [7]:
def bubbleSort(arr):
    swapped = True
    while swapped:
        swapped = False
        for i in range(len(arr) - 1):
            if arr[i] > arr[i + 1]:
                arr[i], arr[i + 1] = arr[i + 1], arr[i]
                swapped = True

### Сортировка Шелла

In [8]:
def shellSort(arr):
    step = len(arr)//2
    while step > 0:
        for i in range(step, len(arr)):
            j = i
            delta = j - step
            while delta >= 0 and arr[delta] > arr[j]:
                arr[delta], arr[j] = arr[j], arr[delta]
                j = delta
                delta = j - step
        step //= 2

### Турнирная сортировка


In [9]:
def tournamentSort(arr):
    tree = [None] * 2 * (len(arr) + len(arr) % 2)
    index = len(tree) - len(arr) - len(arr) % 2
    
    for i, v in enumerate(arr):
        tree[index + i] = (i, v)
    
    for j in range(len(arr)):
        n = len(arr)
        index = len(tree) - len(arr) - len(arr) % 2
        while index > -1:
            n = (n + 1) // 2
            for i in range(n):
                i = max(index + i * 2, 1)
                if tree[i] != None and tree[i + 1] != None:
                    if tree[i][1] < tree[i + 1][1]:
                        tree[i // 2] = tree[i]
                    else:
                        tree[i // 2] = tree[i + 1]
                else:
                    tree[i // 2] = tree[i] if tree[i] != None else tree[i + 1]
            index -= n

        index, x = tree[0]
        arr[j] = x
        tree[len(tree) - len(arr) - len(arr) % 2 + index] = None

### Быстрая сортировка

In [10]:
def partition(arr, low, high):
    pivot = arr[(low + high) // 2]
    i = low - 1
    j = high + 1
    while True:
        i += 1
        while arr[i] < pivot:
            i += 1
        j -= 1
        while arr[j] > pivot:
            j -= 1
        if i >= j:
            return j
        arr[i], arr[j] = arr[j], arr[i]


def quickSort(arr):  
    def _quickSort(items, low, high):
        if low < high:
            split_index = partition(items, low, high)
            _quickSort(items, low, split_index)
            _quickSort(items, split_index + 1, high)
    _quickSort(arr, 0, len(arr) - 1)

### Пирамидальная сортировка

In [11]:
def heapify(arr, heapSize, rootIndex):  
    largest = rootIndex
    leftChild = (2 * rootIndex) + 1
    rightChild = (2 * rootIndex) + 2
    if leftChild < heapSize and arr[leftChild] > arr[largest]:
        largest = leftChild
    if rightChild < heapSize and arr[rightChild] > arr[largest]:
        largest = rightChild
    if largest != rootIndex:
        arr[rootIndex], arr[largest] = arr[largest], arr[rootIndex]
        heapify(arr, heapSize, largest)
def heapSort(arr):  
    n = len(arr)
    for i in range(n, -1, -1):
        heapify(arr, n, i)
    for i in range(n - 1, 0, -1):
        arr[i], arr[0] = arr[0], arr[i]
        heapify(arr, i, 0)

In [12]:
newMatrix = generateMatrix()
print("Сгенерированная матрица\n", newMatrix)

print(sortMatrix(newMatrix, defaultSort), "секунд длилась стандартная функция сортировки")
print(sortMatrix(newMatrix, selectionSort), "секунд длилась сортировка выбором")
print(sortMatrix(newMatrix, insertionSort), "секунд длилась сортировка вставкой")
print(sortMatrix(newMatrix, bubbleSort), "секунд длилась сортировка обменом")
print(sortMatrix(newMatrix, shellSort), "секунд длилась сортировка Шелла")
print(sortMatrix(newMatrix, tournamentSort), "секунд длилась турнирная сортировка")
print(sortMatrix(newMatrix, quickSort), "секунд длилась быстрая сортировка")
print(sortMatrix(newMatrix, heapSort), "секунд длилась пирамидальная сортировка")

Сгенерированная матрица
 [[ 569  -71  925 ...  391  528  -55]
 [ 292   99  270 ...  608  -41  746]
 [   0  192  800 ...  791   14  724]
 ...
 [ 267  450 -219 ... -208  400 -117]
 [  62  301  754 ... -144 -241  982]
 [ 916  235  855 ...  813  327  914]]
0.0014881999999998285 секунд длилась стандартная функция сортировки
0.036292699999999734 секунд длилась сортировка выбором
0.019173399999999674 секунд длилась сортировка вставкой
0.06501760000000001 секунд длилась сортировка обменом
0.01112499999999983 секунд длилась сортировка Шелла
0.10216950000000002 секунд длилась турнирная сортировка
0.01078929999999989 секунд длилась быстрая сортировка
0.02004819999999974 секунд длилась пирамидальная сортировка


### Задание №4

Создать публичный репозиторий на github, и запустить выполненное задание в .ipynb формате.

### Вывод

В ходе лабораторной работы мы научились реализовать разные методы сортировки строк числовой матрицы 